# Generated by Django 3.2.12 on 2022-04-10 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220409_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pass_front', stdimage.models.StdImageField(blank=True, upload_to='passport/front')),
                ('pass_back', stdimage.models.StdImageField(blank=True, upload_to='passport/back')),
                ('selfie', stdimage.models.StdImageField(blank=True, upload_to='passport/selfie')),
                ('birth_cert', stdimage.models.StdImageField(blank=True, upload_to='passport/bcert')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
