# Generated by Django 3.2.12 on 2022-04-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_kycverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('LTC', 'LTC'), ('DASH', 'DASH'), ('AFFILIATE', 'AFFILIATE')], default='BTC', max_length=16),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('AFFILIATE', 'AFFILIATE'), ('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW')], default='DEPOSIT', max_length=15),
        ),
    ]
