# Generated by Django 3.2.12 on 2022-04-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220410_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
