# Generated by Django 3.2.12 on 2022-04-10 12:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220410_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=uuid.uuid1, editable=False, max_length=50, unique=True),
        ),
    ]
