# Generated by Django 3.2.12 on 2022-04-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=19873892038485873942, editable=False, max_length=50, unique=True),
        ),
    ]
