# Generated by Django 3.2.12 on 2022-04-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220410_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverify',
            name='birth_cert',
        ),
        migrations.RemoveField(
            model_name='kycverify',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='kycverify',
            name='selfie',
        ),
    ]
