# Generated by Django 3.2.12 on 2022-04-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='withdraw_roi',
            field=models.BooleanField(default=False),
        ),
    ]
