# Generated by Django 3.2.12 on 2022-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220411_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_withdraw',
        ),
        migrations.RemoveField(
            model_name='user',
            name='withdraw_roi',
        ),
        migrations.AddField(
            model_name='wallet',
            name='invested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('LTC', 'LTC'), ('DASH', 'DASH')], default='BTC', max_length=16),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('AFFILIATE', 'AFFILIATE'), ('DEPOSIT', 'DEPOSIT'), ('WITHDRAW', 'WITHDRAW'), ('ROI', 'ROI')], default='DEPOSIT', max_length=15),
        ),
    ]
