# Generated by Django 3.2.12 on 2022-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_first_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_topup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_withdraw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_withdraw_roi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_invested',
            field=models.BooleanField(default=False),
        ),
    ]
