# Generated by Django 3.2.12 on 2022-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mode', '0002_currency_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
