# Generated by Django 3.2.12 on 2022-04-13 08:11

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mode', '0004_agreement_privacy_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trade Week Open/Close',
                'verbose_name_plural': 'Trade Week Open/Close',
                'managed': True,
            },
        ),
    ]
